version: '3'

services:
  server:
    # restart: always
    build:
      context: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    networks:
      - internal_net

  client:
    # restart: always
    build:
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    networks:
      - internal_net

networks:
  internal_net: