version: '3'

services:
  server:
    # restart: always
    build:
      context: ./server
    entrypoint: ["sh", "/app/entrypoint.sh"]
    ports:
      - 8000:8000
    networks:
      - internal_net

  client:
    # restart: always
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - internal_net
    depends_on:
      - server

networks:
  internal_net: